
import { Deal } from './types';

export const CITIES = ['New York', 'Los Angeles', 'Chicago', 'San Francisco', 'Miami'];

export const PREDEFINED_AVATARS = [
    'https://i.pravatar.cc/150?u=avatar1',
    'https://i.pravatar.cc/150?u=avatar2',
    'https://i.pravatar.cc/150?u=avatar3',
    'https://i.pravatar.cc/150?u=avatar4',
    'https://i.pravatar.cc/150?u=avatar5',
    'https://i.pravatar.cc/150?u=avatar6',
    'https://i.pravatar.cc/150?u=avatar7',
    'https://i.pravatar.cc/150?u=avatar8',
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 1,
    title: "25% off dinner",
    description: "Enjoy authentic Italian cuisine with our exclusive discount. Valid for dinner only. Cannot be combined with other offers.",
    category: "Restaurants",
    discountValue: "25% OFF",
    originalPrice: 40,
    priceUSDC: 30,
    totalMint: 50,
    sold: 15,
    expiryDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/pasta/800/600",
    merchantName: "Pasta Paradise",
    merchantLogo: "https://picsum.photos/seed/pplogo/100/100",
    location: "New York",
    terms: "Not valid on holidays. One coupon per table.",
    redemptionInstructions: "Show the QR code to your server before ordering."
  },
  {
    id: 2,
    title: "40% off 3 nights stay",
    description: "Escape to paradise with a luxurious 3-night stay at our beachfront resort in Bali. Includes breakfast.",
    category: "Travel",
    discountValue: "40% OFF",
    originalPrice: 250,
    priceUSDC: 150,
    totalMint: 30,
    sold: 10,
    expiryDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/bali/800/600",
    merchantName: "Bali Hotel & Spa",
    merchantLogo: "https://picsum.photos/seed/balilogo/100/100",
    location: "San Francisco",
    terms: "Subject to availability. Blackout dates may apply.",
    redemptionInstructions: "Present QR code at check-in."
  },
  {
    id: 3,
    title: "$50 off new sneakers",
    description: "Get $50 off any pair of sneakers from the latest collection. In-store only.",
    category: "Shopping",
    discountValue: "$50 OFF",
    originalPrice: 150,
    priceUSDC: 50,
    totalMint: 100,
    sold: 45,
    expiryDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/sneakers/800/600",
    merchantName: "Nike Store",
    merchantLogo: "https://picsum.photos/seed/nikelogo/100/100",
    location: "Los Angeles",
    terms: "Valid on items over $120. Cannot be combined with other promotions.",
    redemptionInstructions: "Scan QR code at checkout."
  },
  {
    id: 4,
    title: "30% off wellness package",
    description: "Rejuvenate with our full-day wellness package, including massage, facial, and sauna access.",
    category: "Services",
    discountValue: "30% OFF",
    originalPrice: 100,
    priceUSDC: 40,
    totalMint: 40,
    sold: 18,
    expiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/spa/800/600",
    merchantName: "Massage & Wellness",
    merchantLogo: "https://picsum.photos/seed/spalogo/100/100",
    location: "Miami",
    terms: "Advance booking required. Mention NFT coupon when booking.",
    redemptionInstructions: "Show QR code upon arrival."
  },
  {
    id: 5,
    title: "$200 off round trip to Tokyo",
    description: "Explore the vibrant city of Tokyo with $200 off your round-trip flight. Travel anytime in the next 6 months.",
    category: "Travel",
    discountValue: "$200 OFF",
    originalPrice: 1200,
    priceUSDC: 200,
    totalMint: 20,
    sold: 5,
    expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/tokyo/800/600",
    merchantName: "SkyHigh Airlines",
    merchantLogo: "https://picsum.photos/seed/airlogo/100/100",
    location: "Chicago",
    terms: "Book at least 30 days in advance. Taxes and fees not included.",
    redemptionInstructions: "Use code from QR page during online checkout."
  },
  {
    id: 6,
    title: "Buy 1 Get 1 Free Sushi Platter",
    description: "Bring a friend and enjoy two of our signature sushi platters for the price of one.",
    category: "Restaurants",
    discountValue: "BOGO",
    originalPrice: 50,
    priceUSDC: 25,
    totalMint: 80,
    sold: 60,
    expiryDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/sushi/800/600",
    merchantName: "Sushi Bar",
    merchantLogo: "https://picsum.photos/seed/sushilogo/100/100",
    location: "New York",
    terms: "Valid for dine-in only. Lesser value platter is free.",
    redemptionInstructions: "Show QR code to server."
  },
    {
    id: 7,
    title: "15% off laptops",
    description: "Upgrade your tech with 15% off any laptop in our store. Perfect for work, school, or gaming.",
    category: "Shopping",
    discountValue: "15% OFF",
    originalPrice: 1000,
    priceUSDC: 100,
    totalMint: 50,
    sold: 22,
    expiryDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/laptops/800/600",
    merchantName: "Electro Gadgets",
    merchantLogo: "https://picsum.photos/seed/gadgetlogo/100/100",
    location: "San Francisco",
    terms: "Excludes Apple products. One coupon per customer.",
    redemptionInstructions: "Present QR code at the electronics checkout counter."
  },
  {
    id: 8,
    title: "20% discount on Paris City Tour",
    description: "Discover the magic of Paris with our guided city tour, covering all major landmarks.",
    category: "Travel",
    discountValue: "20% OFF",
    originalPrice: 90,
    priceUSDC: 45,
    totalMint: 60,
    sold: 30,
    expiryDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/paris/800/600",
    merchantName: "CityScape Tours",
    merchantLogo: "https://picsum.photos/seed/tourlogo/100/100",
    location: "Los Angeles",
    terms: "Tour operates daily. Booking must be made 48 hours in advance.",
    redemptionInstructions: "Provide NFT ID when booking online and show QR on tour day."
  },
  {
    id: 9,
    title: "35% off 6 Month Membership",
    description: "Commit to be fit with a 6-month all-access gym membership at a fraction of the price.",
    category: "Services",
    discountValue: "35% OFF",
    originalPrice: 300,
    priceUSDC: 120,
    totalMint: 75,
    sold: 15,
    expiryDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/gym/800/600",
    merchantName: "Flex Fitness",
    merchantLogo: "https://picsum.photos/seed/flexlogo/100/100",
    location: "Miami",
    terms: "For new members only. Cannot be frozen or transferred.",
    redemptionInstructions: "Show your QR code at the front desk to sign up."
  },
  {
    id: 10,
    title: "Free dessert + 20% off",
    description: "Enjoy a free dessert of your choice with your meal, plus an additional 20% off the total bill.",
    category: "Restaurants",
    discountValue: "20% + Freebie",
    originalPrice: 40,
    priceUSDC: 20,
    totalMint: 120,
    sold: 90,
    expiryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    image: "https://picsum.photos/seed/pizza/800/600",
    merchantName: "Pizza Place",
    merchantLogo: "https://picsum.photos/seed/pizzalogo/100/100",
    location: "Chicago",
    terms: "Minimum spend of $30. One free dessert per coupon.",
    redemptionInstructions: "Present QR code when asking for the bill."
  }
];
